apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../../common-config
patches:
  - path: rollout-replica.yaml
  - path: hpa.yaml
  - path: service-loadbalancer.yaml
