apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: surya 
configMapGenerator:
  - name: cm6
    literals:
      - MYSQL_USER=ROOT
      - MYSQL_PASSWORD=redhat2

secretGenerator:
  - name: app-secret
    files:
      - db.prop


resources:
  - service.yaml
  - deployment.yaml
  - hpa.yaml
