apiVersion: apps/v1
kind: Deployment
metadata:
  name: mani1-frontend-deployment
  namespace: surya
spec:
  selector:
    matchLabels:
      app: mani1-frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
        - name: app
          image: public.ecr.aws/aws-containers/retail-store-sample-checkout:1.2.1
          envFrom:
            - configMapRef:
                name: cm6
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: app-secret-volume
              mountPath: /data
              readOnly: true
      volumes:
        - name: app-secret-volume
          secret:
            secretName: app-secret
